name: webappdeploy

on:
  push:
    branches:
      - main
jobs:
  build_webapp:
        runs-on: ubuntu-latest
        
        steps:
        - name: install_package
          run : |
                sudo apt-get update && sudo apt-get upgrade
                apt-get install pip3 && python3
                pip3 install Flask
