name: webappdeploy

on:
  push:
    branches:
      - main
jobs:
  build_webapp:
        runs-on: ubuntu-latest
        
        steps:
        - name: install_package
          run : |
                pip3 --version
                python3 --version
                pip3 install Flask
                
        - name: git clone my repo
          uses: actions/checkout@v1
          
        - name:  list current folder and packages
          run: ls -la
        
        - name: deploy webapp
          run: sudo docker build .
        
        
    
  push_app_to_docker_hub:
      runs-on: ubuntu-latest
      needs: [build_webapp]
    
      steps:
      - name: git clone webapp repo
        uses: actions/checkout@v1
    
      - name: deploy webapp
        run: |
            sudo docker build .
            docker push frame0310/webapp:tagname
      
      
