#Github Action ryka-lico proba
#
#-------------------------------
name: webapp-test-dev

on:
  push:
    branches:
      - main

jobs:
  testcode_and_development:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: install python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      
      - name: install pckg
        run: |
          python -m pip install --upgrade pip
          pip3 install Flask && flake8
          

      - name: run flake8 test code
        run: flake8 .
      